<?php
// This file is auto-generated by installer
// Modify only if you know what you're doing

// Database configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'shipment_system');
define('DB_USER', 'root');
define('DB_PASS', '');

// Application settings
define('UPLOAD_DIR', __DIR__ . '/uploads/');
define('MAX_FILE_SIZE', 10 * 1024 * 1024); // 10MB
define('ALLOWED_TYPES', ['csv', 'xlsx']);
define('SESSION_LIFETIME', 3600); // 1 hour

// Error reporting (disable in production)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Create uploads directory if not exists
if (!file_exists(UPLOAD_DIR)) {
    mkdir(UPLOAD_DIR, 0755, true);
}

// Set timezone
date_default_timezone_set('UTC');
